import { useState, useRef, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  BrainCircuit, Upload, FileText, X, Send, Sparkles, Download,
  MessageSquare, Trash2, Bot, User, AlertCircle, CheckCircle2
} from "lucide-react";

const CONTACT = "0768925411";
const AUTHOR = "AHMED AI";

type Message = { id: string; role: "user" | "ai"; text: string; timestamp: number };
type UploadedFile = { id: string; name: string; size: number; content: string; type: string };

const TRADING_KB: Record<string, string> = {
  martingale: "Martingale strategy doubles your stake after each loss. High risk — can blow account in a losing streak. Best for 80%+ winrate conditions only.",
  "rise fall": "Rise/Fall contracts predict if the exit price will be higher (Rise) or lower (Fall) than the entry price. Good for trending markets.",
  accumulator: "Accumulator contracts grow your profit as long as price stays within a defined barrier. Low risk, consistent small gains.",
  "over under": "Over/Under contracts pay if the last digit is above (Over) or below (Under) a threshold digit (0-9).",
  "matches differs": "Matches pays if the last digit equals your predicted digit. Differs pays if last digit is anything else. Matches has 1:10 odds.",
  "even odd": "Even/Odd contracts pay if the last digit is even (0,2,4,6,8) or odd (1,3,5,7,9). ~50/50 probability.",
  volatility: "Volatility indices simulate constant market volatility 24/7. V10 is calmest, V100 is most volatile.",
  "crash boom": "Crash indices spike down every X ticks on average. Boom indices spike up. Named for approximate average spike interval.",
  jump: "Jump indices are like volatility but with sudden large jumps. Higher payout potential but harder to predict.",
  fibonacci: "Fibonacci betting system: stake follows sequence 1,1,2,3,5,8,13... after losses. Less aggressive than Martingale.",
  "risk management": "Rule 1: Never risk more than 2% per trade. Rule 2: Set daily stop loss at 20% of balance. Rule 3: Take profit and stop after hitting targets.",
  signal: "A signal is a trading recommendation based on statistical analysis of tick data. Signals show trade type, entry point, duration, and confidence level.",
  "wide eye": "Wide Eye analysis shows digit frequency distribution over many ticks to identify statistical biases in digit generation.",
  payout: "Payout on Deriv synthetic indices is typically 85-95% for binary options. Breakeven winrate = 1/(1+payout).",
  "digit analysis": "Digit analysis looks at the last digit of tick prices. Over large samples, digits should be equally distributed (10% each). Deviations indicate potential trading opportunities.",
  "smart trade": "Smart Trade uses multiple technical indicators (MACD, TSI, Moving Averages) to analyze price charts and generate directional signals.",
};

function findAnswer(question: string): string {
  const q = question.toLowerCase();
  const matched = Object.entries(TRADING_KB).filter(([key]) =>
    key.split(" ").some((word) => q.includes(word))
  );
  if (matched.length > 0) {
    return matched.map(([, v]) => v).join("\n\n");
  }
  if (q.includes("hello") || q.includes("hi") || q.includes("hey")) {
    return `Hello! I'm Ahmed AI, your trading assistant for Deriv synthetic markets. I can help you with:\n• Trading strategies (Martingale, Fibonacci, D'Alembert)\n• Contract types (Rise/Fall, Over/Under, Accumulators, Matches/Differs)\n• Risk management and position sizing\n• Reading signals and market analysis\n\nWhat would you like to learn today?`;
  }
  if (q.includes("best") && q.includes("strategy")) {
    return "The best strategy depends on your risk tolerance:\n• Low risk: Fixed 1-2% stake, Over/Under or Even/Odd contracts\n• Medium risk: Accumulator contracts, 3-5 tick Rise/Fall\n• High risk: Martingale on Matches/Differs (high reward, can lose fast)\n\nAlways set a daily stop loss and stick to it!";
  }
  if (q.includes("how") && q.includes("signal")) {
    return "AHMED AI signals are generated by analyzing tick frequency distributions:\n1. Collect 100+ ticks per market\n2. Calculate percentage frequency of each digit (0-9)\n3. Identify statistical deviations (>13% or <7%)\n4. Generate contract recommendations with confidence scores\n5. Signals are valid for 20 minutes then regenerate";
  }
  if (q.includes("stop loss") || q.includes("stoploss")) {
    return TRADING_KB["risk management"] + "\n\nCalculate your stop loss:\n• Daily SL = 20% of balance\n• Per-session SL = 10% of balance\n• Per-trade SL = 2% of balance\n\nNever chase losses!";
  }
  return `I don't have specific data on "${question}" yet. Try asking about:\n• Trading strategies (martingale, fibonacci, fixed)\n• Contract types (rise/fall, over/under, even/odd, matches, accumulators)\n• Risk management\n• Volatility/Crash/Boom/Jump indices\n• Reading signals\n\nYou can also upload documents to teach me more!`;
}

function generateFlyerCanvas(signal: {
  type: string; market: string; entry: string; ticks: string; confidence: number; theme: number;
}, logoUrl: string) {
  const W = 800, H = 480;
  const canvas = document.createElement("canvas");
  canvas.width = W; canvas.height = H;
  const ctx = canvas.getContext("2d")!;

  const themes = [
    { bg1: "#000000", bg2: "#001a1a", primary: "#00d1d1", accent: "#00ffff" },
    { bg1: "#0a0020", bg2: "#1a0040", primary: "#f59e0b", accent: "#fde68a" },
    { bg1: "#000000", bg2: "#001200", primary: "#00ff41", accent: "#39ff14" },
    { bg1: "#050012", bg2: "#0d0030", primary: "#a855f7", accent: "#e879f9" },
    { bg1: "#0a0000", bg2: "#200000", primary: "#ef4444", accent: "#f97316" },
  ];
  const t = themes[(signal.theme - 1) % 5];

  const grad = ctx.createLinearGradient(0, 0, W, H);
  grad.addColorStop(0, t.bg1); grad.addColorStop(1, t.bg2);
  ctx.fillStyle = grad; ctx.fillRect(0, 0, W, H);

  ctx.strokeStyle = `${t.primary}22`; ctx.lineWidth = 0.5;
  for (let x = 0; x < W; x += 35) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); }
  for (let y = 0; y < H; y += 35) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke(); }

  ctx.strokeStyle = t.primary; ctx.lineWidth = 3;
  ctx.shadowColor = t.primary; ctx.shadowBlur = 15;
  ctx.strokeRect(10, 10, W - 20, H - 20);
  ctx.shadowBlur = 0;

  const draw = (logoImg: HTMLImageElement | null) => {
    if (logoImg) {
      ctx.save(); ctx.beginPath(); ctx.arc(64, 64, 46, 0, Math.PI * 2); ctx.clip();
      ctx.drawImage(logoImg, 18, 18, 92, 92); ctx.restore();
    }

    ctx.font = "bold 11px monospace"; ctx.fillStyle = t.primary; ctx.letterSpacing = "3px";
    ctx.fillText("AHMED SYNTRADER", 130, 45); ctx.letterSpacing = "0px";
    ctx.font = "bold 28px monospace"; ctx.fillStyle = "#ffffff";
    ctx.fillText("AI SIGNAL FLYER", 130, 82);
    ctx.font = "11px monospace"; ctx.fillStyle = `${t.primary}aa`;
    ctx.fillText(`${CONTACT}  ·  ahmedsyntrader.site`, 130, 105);

    ctx.strokeStyle = `${t.primary}50`; ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(25, 125); ctx.lineTo(W - 25, 125); ctx.stroke();

    ctx.font = "bold 52px monospace"; ctx.fillStyle = t.primary;
    ctx.shadowColor = t.primary; ctx.shadowBlur = 25;
    ctx.fillText(signal.type, 40, 200); ctx.shadowBlur = 0;

    ctx.font = "15px monospace"; ctx.fillStyle = t.accent;
    ctx.fillText(signal.market.toUpperCase(), W - 200, 160);

    const items = [
      { l: "📌  ENTRY", v: signal.entry },
      { l: "⏱  DURATION", v: signal.ticks },
      { l: "📊  CONFIDENCE", v: `${signal.confidence}%` },
      { l: "⏳  VALID FOR", v: "20 MINUTES" },
    ];
    let ry = 240;
    items.forEach(({ l, v }) => {
      ctx.font = "11px monospace"; ctx.fillStyle = `${t.primary}99`; ctx.fillText(l, 40, ry);
      ctx.font = "bold 15px monospace"; ctx.fillStyle = "#ffffff"; ctx.fillText(v, 40, ry + 20);
      ry += 50;
    });

    ctx.strokeStyle = `${t.primary}40`; ctx.beginPath(); ctx.moveTo(25, H - 65); ctx.lineTo(W - 25, H - 65); ctx.stroke();
    ctx.font = "bold 13px monospace"; ctx.fillStyle = t.primary; ctx.textAlign = "center";
    ctx.fillText(`Made by ${AUTHOR}  ·  ${CONTACT}  ·  ahmedsyntrader.site`, W / 2, H - 38);
    ctx.font = "10px monospace"; ctx.fillStyle = `${t.primary}60`;
    ctx.fillText("Risk Disclaimer: Signals are for educational purposes only. Trade at your own risk.", W / 2, H - 18);
    ctx.textAlign = "left";

    const link = document.createElement("a");
    link.download = `AhmedAI_${signal.type.replace(/\s+/g, "_")}_${Date.now()}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  const img = new window.Image(); img.crossOrigin = "anonymous";
  img.onload = () => draw(img); img.onerror = () => draw(null);
  img.src = logoUrl;
}

const SIGNAL_PRESETS = [
  { type: "MATCHES 7", market: "Volatility 10", entry: "Any digit except 7", ticks: "1 tick", confidence: 78, theme: 1 },
  { type: "EVEN", market: "Volatility 25", entry: "Odd digit", ticks: "1 tick", confidence: 74, theme: 2 },
  { type: "RISE", market: "Crash 500", entry: "Current price", ticks: "5 ticks", confidence: 70, theme: 3 },
  { type: "OVER 4", market: "Boom 300", entry: "Digit 0-3", ticks: "2 ticks", confidence: 72, theme: 4 },
  { type: "ACCUMULATOR", market: "Volatility 50", entry: "Current barrier", ticks: "10 ticks", confidence: 75, theme: 5 },
  { type: "DIFFERS 3", market: "Jump 10", entry: "Current price", ticks: "1 tick", confidence: 81, theme: 1 },
];

export default function AILearning() {
  const [messages, setMessages] = useState<Message[]>([{
    id: "welcome",
    role: "ai",
    text: `Welcome to Ahmed AI Learning Center!\n\nI can help you understand:\n• Deriv synthetic market strategies\n• Risk management techniques\n• How signals are generated\n• Contract types and payouts\n\nUpload your trading notes/PDFs to teach me more, or just ask any question below!`,
    timestamp: Date.now(),
  }]);
  const [input, setInput] = useState("");
  const [files, setFiles] = useState<UploadedFile[]>([]);
  const [isTyping, setIsTyping] = useState(false);
  const [customSignal, setCustomSignal] = useState({ type: "RISE", market: "Volatility 10", entry: "Current price", ticks: "5 ticks", confidence: 75, theme: 1 });
  const fileInputRef = useRef<HTMLInputElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const logoUrl = `${import.meta.env.BASE_URL}logo.png`.replace("//", "/");

  const scrollToBottom = () => setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: "smooth" }), 100);

  const sendMessage = useCallback(() => {
    if (!input.trim()) return;
    const userMsg: Message = { id: Date.now().toString(), role: "user", text: input, timestamp: Date.now() };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);
    scrollToBottom();

    const fileContext = files.map((f) => `[From ${f.name}]: ${f.content.slice(0, 500)}`).join("\n");
    const baseAnswer = findAnswer(input);
    const finalAnswer = fileContext
      ? `${baseAnswer}\n\n📎 From your uploaded documents:\n${fileContext.slice(0, 300)}...`
      : baseAnswer;

    setTimeout(() => {
      const aiMsg: Message = { id: (Date.now() + 1).toString(), role: "ai", text: finalAnswer, timestamp: Date.now() };
      setMessages((prev) => [...prev, aiMsg]);
      setIsTyping(false);
      scrollToBottom();
    }, 800 + Math.random() * 700);
  }, [input, files]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newFiles = Array.from(e.target.files ?? []);
    newFiles.forEach((file) => {
      const reader = new FileReader();
      reader.onload = (ev) => {
        const content = typeof ev.target?.result === "string" ? ev.target.result : "[Binary file — image/PDF]";
        setFiles((prev) => [...prev, {
          id: Date.now().toString() + file.name,
          name: file.name, size: file.size,
          content: content.slice(0, 2000),
          type: file.type,
        }]);
        setMessages((prev) => [...prev, {
          id: "file-" + Date.now(),
          role: "ai",
          text: `📎 I've received "${file.name}" (${(file.size / 1024).toFixed(1)} KB). I'll use this context when answering your questions. What would you like to know?`,
          timestamp: Date.now(),
        }]);
        scrollToBottom();
      };
      if (file.type.startsWith("text") || file.name.endsWith(".txt") || file.name.endsWith(".md") || file.name.endsWith(".csv")) {
        reader.readAsText(file);
      } else {
        reader.readAsDataURL(file);
      }
    });
    e.target.value = "";
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <BrainCircuit className="w-6 h-6 text-primary" /> AI Learning Center
        </h1>
        <p className="text-muted-foreground text-sm">Upload trading knowledge, ask AI anything, generate signal flyers</p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
        {/* Left: Upload + Flyer Generator */}
        <div className="space-y-4">
          {/* File Upload */}
          <Card className="bg-card border-border">
            <CardHeader className="py-3 px-4 border-b border-border flex flex-row items-center gap-2">
              <Upload className="w-4 h-4 text-primary" />
              <CardTitle className="text-xs font-bold uppercase text-muted-foreground">Teach Ahmed AI</CardTitle>
            </CardHeader>
            <CardContent className="p-4 space-y-3">
              <div
                onClick={() => fileInputRef.current?.click()}
                className="border-2 border-dashed border-border hover:border-primary/50 rounded-xl p-6 text-center cursor-pointer transition-all group"
              >
                <Upload className="w-8 h-8 text-muted-foreground group-hover:text-primary mx-auto mb-2 transition-colors" />
                <p className="text-sm font-bold">Upload Files</p>
                <p className="text-xs text-muted-foreground mt-1">TXT, PDF, MD, CSV, images</p>
              </div>
              <input ref={fileInputRef} type="file" multiple accept=".txt,.md,.csv,.pdf,.png,.jpg,.jpeg" onChange={handleFileUpload} className="hidden" />

              {files.length > 0 && (
                <div className="space-y-2">
                  <div className="text-xs font-bold text-muted-foreground uppercase">Uploaded ({files.length})</div>
                  {files.map((f) => (
                    <div key={f.id} className="flex items-center gap-2 p-2 bg-muted rounded-lg">
                      <FileText className="w-3.5 h-3.5 text-primary flex-shrink-0" />
                      <div className="flex-1 min-w-0">
                        <div className="text-xs font-bold truncate">{f.name}</div>
                        <div className="text-[10px] text-muted-foreground">{(f.size / 1024).toFixed(1)} KB</div>
                      </div>
                      <button onClick={() => setFiles((prev) => prev.filter((x) => x.id !== f.id))} className="text-muted-foreground hover:text-destructive transition-colors flex-shrink-0">
                        <X className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  ))}
                  <button onClick={() => setFiles([])} className="text-xs text-red-400 hover:text-red-300 flex items-center gap-1 transition-colors">
                    <Trash2 className="w-3 h-3" /> Clear all
                  </button>
                </div>
              )}

              {files.length === 0 && (
                <p className="text-[10px] text-muted-foreground text-center">
                  Upload your trading notes, strategies, or charts to enhance AI responses
                </p>
              )}
            </CardContent>
          </Card>

          {/* Signal Flyer Generator */}
          <Card className="bg-card border-border">
            <CardHeader className="py-3 px-4 border-b border-border flex flex-row items-center gap-2">
              <Sparkles className="w-4 h-4 text-primary" />
              <CardTitle className="text-xs font-bold uppercase text-muted-foreground">Generate Signal Flyer</CardTitle>
            </CardHeader>
            <CardContent className="p-4 space-y-3">
              <div className="space-y-2 text-xs">
                {[
                  { field: "type", label: "Signal Type", placeholder: "e.g. RISE, EVEN, MATCHES 7" },
                  { field: "market", label: "Market", placeholder: "e.g. Volatility 10" },
                  { field: "entry", label: "Entry Point", placeholder: "e.g. Any odd digit" },
                  { field: "ticks", label: "Duration", placeholder: "e.g. 5 ticks" },
                ].map(({ field, label, placeholder }) => (
                  <div key={field}>
                    <label className="text-muted-foreground font-bold uppercase mb-1 block">{label}</label>
                    <input
                      type="text"
                      placeholder={placeholder}
                      value={(customSignal as any)[field]}
                      onChange={(e) => setCustomSignal((prev) => ({ ...prev, [field]: e.target.value }))}
                      className="w-full bg-background border border-border text-foreground rounded px-2.5 py-1.5 text-xs font-mono focus:outline-none focus:border-primary"
                    />
                  </div>
                ))}
                <div>
                  <label className="text-muted-foreground font-bold uppercase mb-1 block">Confidence %</label>
                  <input
                    type="number"
                    min={50}
                    max={99}
                    value={customSignal.confidence}
                    onChange={(e) => setCustomSignal((prev) => ({ ...prev, confidence: +e.target.value }))}
                    className="w-full bg-background border border-border text-foreground rounded px-2.5 py-1.5 text-xs font-mono focus:outline-none focus:border-primary"
                  />
                </div>
                <div>
                  <label className="text-muted-foreground font-bold uppercase mb-1 block">Theme (1–5)</label>
                  <div className="flex gap-1">
                    {[1, 2, 3, 4, 5].map((n) => (
                      <button
                        key={n}
                        onClick={() => setCustomSignal((prev) => ({ ...prev, theme: n }))}
                        className={`flex-1 py-1.5 rounded text-xs font-bold border transition-all ${
                          customSignal.theme === n ? "border-primary bg-primary/20 text-primary" : "border-border text-muted-foreground"
                        }`}
                      >
                        {n}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <button
                onClick={() => generateFlyerCanvas(customSignal, logoUrl)}
                className="w-full flex items-center justify-center gap-2 py-2.5 bg-primary text-primary-foreground rounded-lg font-bold text-sm hover:bg-primary/90 transition-all"
                style={{ boxShadow: "0 0 15px rgba(0,209,209,0.3)" }}
              >
                <Download className="w-4 h-4" /> Download Custom Flyer
              </button>

              <div className="border-t border-border pt-3">
                <div className="text-xs font-bold text-muted-foreground mb-2 uppercase">Quick Presets</div>
                <div className="space-y-1">
                  {SIGNAL_PRESETS.map((preset, i) => (
                    <button
                      key={i}
                      onClick={() => generateFlyerCanvas(preset, logoUrl)}
                      className="w-full flex items-center justify-between px-3 py-1.5 bg-muted rounded hover:bg-muted/80 transition-colors text-xs"
                    >
                      <span className="font-bold text-primary">{preset.type}</span>
                      <span className="text-muted-foreground">{preset.market}</span>
                      <div className="flex items-center gap-1 text-primary">
                        <Download className="w-3 h-3" />
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right: Chat (2/3 width) */}
        <div className="xl:col-span-2">
          <Card className="bg-card border-border h-full flex flex-col" style={{ minHeight: "600px" }}>
            <CardHeader className="py-3 px-5 border-b border-border flex flex-row items-center gap-2 flex-shrink-0">
              <Bot className="w-4 h-4 text-primary" />
              <CardTitle className="text-xs font-bold uppercase text-muted-foreground">Ask Ahmed AI Anything</CardTitle>
              <div className="ml-auto flex items-center gap-1.5">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                <span className="text-[10px] font-mono text-muted-foreground">Online</span>
              </div>
            </CardHeader>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {messages.map((msg) => (
                <div key={msg.id} className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                    msg.role === "ai"
                      ? "bg-primary/20 border border-primary/30"
                      : "bg-muted border border-border"
                  }`}>
                    {msg.role === "ai" ? <Bot className="w-4 h-4 text-primary" /> : <User className="w-4 h-4 text-muted-foreground" />}
                  </div>
                  <div className={`max-w-[80%] ${msg.role === "user" ? "text-right" : ""}`}>
                    <div className={`inline-block px-4 py-3 rounded-2xl text-sm leading-relaxed whitespace-pre-line ${
                      msg.role === "ai"
                        ? "bg-muted/80 text-foreground rounded-tl-sm"
                        : "bg-primary/20 border border-primary/30 text-foreground rounded-tr-sm"
                    }`}>
                      {msg.text}
                    </div>
                    <div className="text-[9px] text-muted-foreground mt-1 px-1">
                      {new Date(msg.timestamp).toLocaleTimeString()}
                    </div>
                  </div>
                </div>
              ))}

              {isTyping && (
                <div className="flex gap-3">
                  <div className="w-8 h-8 rounded-full flex items-center justify-center bg-primary/20 border border-primary/30">
                    <Bot className="w-4 h-4 text-primary" />
                  </div>
                  <div className="bg-muted/80 rounded-2xl rounded-tl-sm px-4 py-3 flex items-center gap-1">
                    {[0, 1, 2].map((i) => (
                      <div key={i} className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce" style={{ animationDelay: `${i * 150}ms` }} />
                    ))}
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Quick questions */}
            <div className="px-4 py-2 border-t border-border/50 flex gap-2 overflow-x-auto hide-scrollbar flex-shrink-0">
              {[
                "Best strategy for beginners?",
                "How to manage risk?",
                "What is Martingale?",
                "How do signals work?",
                "Explain Over/Under",
              ].map((q) => (
                <button
                  key={q}
                  onClick={() => { setInput(q); }}
                  className="whitespace-nowrap text-[10px] font-bold px-3 py-1.5 bg-muted hover:bg-muted/80 rounded-full border border-border transition-colors text-muted-foreground"
                >
                  {q}
                </button>
              ))}
            </div>

            {/* Input */}
            <div className="p-4 border-t border-border flex-shrink-0">
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="Ask anything about trading..."
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && sendMessage()}
                  className="flex-1 bg-background border border-border text-foreground rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-primary placeholder:text-muted-foreground"
                />
                <button
                  onClick={sendMessage}
                  disabled={!input.trim() || isTyping}
                  className="px-4 py-2.5 bg-primary text-primary-foreground rounded-xl font-bold disabled:opacity-40 hover:bg-primary/90 transition-all flex items-center gap-2"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
